### ISSUE TITLE
Game Crashes Whenever Anyone Selects Fae Origin

### ISSUE THREAD

**Issue by Karvoo** [Deadbones2000/Medieval-Origins#32]
Good evening,

For some reason anytime anyone selects the Fae Origin upon startup [Fabric 1.19.2] or after changing with an orb of origin, they crash the entire server and the server becomes unable to join until restored to a previous save.

It is not creating a crash report locally on the client side, but it is server side so I have attached that below

[crash-2022-09-04_19.59.06-server (1).txt](https://github.com/Deadbones2000/Medieval-Origins/files/9485430/crash-2022-09-04_19.59.06-server.1.txt)

**Comment by szikra** [comment]
I have a similar/same problem when choosing pixie origin or when loading in the world (in single player mode).

This is the error in client log (after choosing origin):
```
[09:43:26] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'int net.minecraft.class_2170.method_9249(net.minecraft.class_2168, java.lang.String)'
	at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$15(EntityActions.java:235) ~[apoli-2.5.1-65ace884c8596bda.jar:?]
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41) ~[apoli-2.5.1-65ace884c8596bda.jar:?]
	at io.github.apace100.origins.power.OriginsCallbackPower.onChosen(OriginsCallbackPower.java:24) ~[Origins-1.19-1.6.2.jar:?]
	at io.github.apace100.origins.component.OriginComponent.lambda$onChosen$0(OriginComponent.java:49) ~[Origins-1.19-1.6.2.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.github.apace100.origins.component.OriginComponent.onChosen(OriginComponent.java:49) ~[Origins-1.19-1.6.2.jar:?]
	at io.github.apace100.origins.networking.ModPacketsC2S.lambda$chooseOrigin$0(ModPacketsC2S.java:50) ~[Origins-1.19-1.6.2.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

```

Same as in crash report
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2022-09-14 09:43:27
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'int net.minecraft.class_2170.method_9249(net.minecraft.class_2168, java.lang.String)'
	at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$15(EntityActions.java:235)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.origins.power.OriginsCallbackPower.onChosen(OriginsCallbackPower.java:24)
	at io.github.apace100.origins.component.OriginComponent.lambda$onChosen$0(OriginComponent.java:49)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.github.apace100.origins.component.OriginComponent.onChosen(OriginComponent.java:49)
	at io.github.apace100.origins.networking.ModPacketsC2S.lambda$chooseOrigin$0(ModPacketsC2S.java:50)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Crash when loading into the world
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2022-09-15 15:57:42
Description: Ticking entity

java.lang.NoSuchMethodError: 'int net.minecraft.class_2170.method_9249(net.minecraft.class_2168, java.lang.String)'
	at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$15(EntityActions.java:235)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.ActionOverTimePower.tick(ActionOverTimePower.java:46)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.apace100.apoli.component.PowerHolderComponentImpl.serverTick(PowerHolderComponentImpl.java:172)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_3222_1356f9d8.tickServerComponents(Unknown Source)
	at net.minecraft.class_3218.handler$cdh000$tick(class_3218.java:8226)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

(Haven't tried other medievalorigins, since I'm using it with a large modpack and it takes a long time to load, and also cannot choose a new origin without creating a new world, since the game crashes as soon as the world loads. I tried to just delete the playerdata file but it wasn't enough. I added the mod to Medieval Minecraft v4.5 modpack, and the other origins work fine.)

**Comment by szikra** [comment]
Did some more testing: 
arachnae, banshee, daemon, paladin works
but fae, necromancer, siren doesn't.

(Using an orb to change origin)

**Comment by eggohito** [comment]
This is an issue with the power library that Origins uses, which should now be fixed if you use Origins 1.7.0 or above.

**Comment by Insydious** [comment]
My friend's server is also having an issue with Siren. She is able to log in, but after a few seconds it crashes. What was weird is she had a few minutes of play time before the error started to happen, and was not able to fix itself after aside from removing the mod pack itself. She is running 1.19.2 with the Medieval Minecraft pack
